# Generated by Django 6.0.2 on 2026-03-01 11:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('frozen', 'Frozen'), ('converted', 'Converted'), ('expired', 'Expired')], default='open', max_length=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('all_received', 'All received'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('quote', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='commerce.quote')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_items', to='catalog.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.quote')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('product_title', models.CharField(max_length=512)),
                ('sku', models.CharField(max_length=128)),
                ('product_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['order'], name='commerce_or_order_i_f502c5_idx'), models.Index(fields=['sku'], name='commerce_or_sku_2b1fd5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('provider', models.CharField(default='dummy', max_length=64)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=128)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='commerce.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order'], name='commerce_pa_order_i_6e8e07_idx'), models.Index(fields=['status'], name='commerce_pa_status_18bcac_idx'), models.Index(fields=['provider_reference'], name='commerce_pa_provide_e35871_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'idempotency_key'), name='uniq_payment_provider_idem')],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['client', 'status'], name='commerce_qu_client__abfa8c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'created_at'], name='commerce_or_client__6f3dcb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='commerce_or_status_ab9590_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('client', 'idempotency_key'), name='uniq_order_client_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='quoteitem',
            index=models.Index(fields=['quote'], name='commerce_qu_quote_i_68438b_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteitem',
            index=models.Index(fields=['product'], name='commerce_qu_product_020162_idx'),
        ),
        migrations.AddConstraint(
            model_name='quoteitem',
            constraint=models.UniqueConstraint(fields=('quote', 'product'), name='uniq_quote_product'),
        ),
    ]
