# Generated by Django 6.0.2 on 2026-03-02 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='uniq_order_client_idempotency_key',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='uniq_payment_provider_idem',
        ),
        migrations.RemoveField(
            model_name='order',
            name='idempotency_key',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='idempotency_key',
        ),
    ]
