"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# PATCH: To make it possible work witn django-idempotency-key without https
from django.http import HttpRequest
if DEBUG:
    HttpRequest.is_secure = lambda self: True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # required for django-allauth registration flow
    "django.contrib.sites",

    "allauth",
    "allauth.account",
    "allauth.socialaccount",

    "rest_framework",

    "dj_rest_auth",
    "dj_rest_auth.registration",

    "drf_spectacular",

    "idempotency_key",

    "accounts",
    "catalog",
    "commerce",

    "devtools"

]

SITE_ID = 1

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    "EXCEPTION_HANDLER": "common.exception_handler.custom_exception_handler",

}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    # ETag / If-None-Match support
    "django.middleware.http.ConditionalGetMiddleware",

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',

    # "idempotency_key.middleware.IdempotencyKeyMiddleware", # Throws 400 when we use http. Enforces all endpoints use idempotency key
    'idempotency_key.middleware.ExemptIdempotencyKeyMiddleware', # Ignores all endpoints except explicitly selected

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


AUTH_USER_MODEL = "accounts.User"

# Recommended (especially if there is AutoField somewhere)
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


SPECTACULAR_SETTINGS = {
    "TITLE": "Simple Commerce API",
    "DESCRIPTION": (
        "API Conventions\n\n"

        "Authentication\n"
        "- All endpoints require JWT authentication.\n"
        "- Send Authorization: Bearer <access_token> header.\n\n"

        "Idempotency\n"
        "- All POST endpoints that create resources may require Idempotency-Key header.\n"
        "- Idempotency-Key must be a unique client-generated string (typically UUID).\n"
        "- Reusing the same Idempotency-Key with the same request body will NOT create a new resource.\n"
        "- The server returns HTTP 409 Conflict and replays the original response body.\n"
        "- 409 in this context does NOT represent a domain error.\n\n"

        "HTTP Conditional Requests\n"
        "- All GET endpoints support ETag-based conditional requests.\n"
        "- Responses include ETag header.\n"
        "- Clients may send If-None-Match header.\n"
        "- If ETag matches, server returns 304 Not Modified with empty body.\n\n"

        "State Machines\n"
        "- Orders, Quotes and Payments use explicit state machines.\n"
        "- Invalid transitions result in 400 or 409 depending on violation type.\n"
        "- Terminal states prevent further modifications.\n\n"

        "Domain Invariants\n"
        "- Currency must match between related aggregates.\n"
        "- Payments cannot be created for cancelled orders.\n"
        "- Terminal entities cannot be modified.\n"

        "Error Semantics\n"
        "- 400: Validation or domain rule violation.\n"
        "- 401: Authentication required or invalid token.\n"
        "- 403: Permission denied.\n"
        "- 404: Resource not found.\n"
        "- 409: Conflict (idempotency replay or state conflict).\n"
        "- 412: Precondition failed (if optimistic locking is used in future).\n\n"

    ),
    "VERSION": "0.1.0",
    # optionally, if you want Swagger to display Bearer/JWT more conveniently
    "SERVE_INCLUDE_SCHEMA": False,
    "TITLE": "Simple Commerce API",
}

from datetime import timedelta

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_HTTPONLY": False,
    "TOKEN_MODEL": None,
    
}
ACCOUNT_AUTHENTICATION_METHOD = "username"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

IDEMPOTENCY_KEY = {
    "HEADER": "HTTP_IDEMPOTENCY_KEY",
    "METHODS": ["POST"]
}