# Generated by Django 6.0.2 on 2026-03-01 23:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('sku', models.CharField(max_length=128)),
                ('product_url', models.URLField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_currency', models.CharField(default='USD', editable=False, max_length=3)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('embedding_ref', models.CharField(blank=True, default='', help_text='Link/key to embedding in a separate repository, or empty for MVP', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.productcategory')),
            ],
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['name'], name='catalog_pro_name_94c6fd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='catalog_pro_is_acti_14fc6b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='catalog_pro_categor_7c1c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('sku',), name='uniq_product_sku'),
        ),
    ]
